language: node_js
node_js:
  - "0.12"
services:
  - mongodb
before_script:
  - npm run bower
  - npm run build
  - $(npm bin)/forever start ./build/src/app.js
after_script:
  - $(npm bin)/forever stop ./build/src/app.js
